name: VA Simulator

options:
  bundleIdPrefix: com.vaecmo

targets:
  VA Simulator:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - path: Sources

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.vaecmo.simulator
      INFOPLIST_KEY_CFBundleDisplayName: VA-ECMO Simulator
      SWIFT_VERSION: 5.0
