name: VA Simulator

options:
  bundleIdPrefix: com.vaecmo
  deploymentTarget:
    iOS: "17.0"

targets:
  VA Simulator:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vaecmo.simulator
        SWIFT_VERSION: "5.0"
